# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.CharField(max_length=4)),
                ('geo', models.CharField(max_length=40)),
                ('est', models.CharField(max_length=150)),
                ('vector', models.CharField(max_length=6)),
                ('coordinate', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
    ]
